export const actionTypes = {
  FETCH_ARTISTS_FULFILLED: "FETCH_ARTISTS_FULFILLED",
  SET_STATUS: "SET_STATUS",
  FETCH_ARTISTS: "FETCH_ARTISTS",
  FETCH_ARTISTS_ERROR: "FETCH_ARTISTS_ERROR",
  FETCH_ALBUMS_FULFILLED: "FETCH_ALBUMS_FULFILLED",
  FETCH_ALBUMS_ERROR: "FETCH_ALBUMS_ERROR",
  FETCH_ALBUMS: "FETCH_ALBUMS",
  ALBUM_SEARCH: "ALBUM_SEARCH",
  SET_SEARCH_VAL: "SET_SEARCH_VAL",
  PAGE_NUM: "PAGE_NUM"
};
